type = "card"
title = "Grants & Awards"
description = "Grants and awards I have received."

[[items]]
title = "The CAST's Young Talents Cultivation Program for Doctoral Students"
subtitle = "China Association for Science and Technology"
date = "2025-2027"
content = "中国科协青年人才培育工程-博士生专项计划"

[[items]]
title = "Hua Luogeng Scholarship"
subtitle = "Academy of Mathematics and Systems Science"
date = "2025"
content = "华罗庚奖学金"


[[items]]
title = "Student Certificate of Recognition"
subtitle = "Society for Industrial and Applied Mathematics"
date = "2025"
# content = "Description of the award."

[[items]]
title = "Outstanding Graduation Student of Beijing"
subtitle = "Beijing Municipal Education Commission"
date = "2022"
content = "北京市优秀毕业生"

[[items]]
title = "National Scholarship"
subtitle = "University of Chinese Academy of Sciences"
date = "2021"
content = "国家奖学金"

[[items]]
title = "First-Class Academic Scholarship"
subtitle = "University of Chinese Academy of Sciences"
date = "2019-2022"
content = "学业一等奖学金"
