[[news]]
date = "2026"
content = "05-22: New preprint - [“Optimization over the intersection of manifolds”](https://arxiv.org/abs/2605.22736)"



[[news]]
date = "2026"
content = "03-26: Honored to be selected to receive the SIAM Student Travel Award for the [2026 SIAM Conference on Optimization (OP26)](https://www.siam.org/conferences-events/siam-conferences/op26/) ✈️, the University of Edinburgh, United Kingdom"


[[news]]
date = "2026"
content = "01-19: New paper accepted in Mathematical Programming - [“A space-decoupling framework for optimization on bounded-rank matrices with orthogonally invariant constraints”](https://link.springer.com/article/10.1007/s10107-026-02331-7)"


[[news]]
date = "2025"
content = "12-15: Honored to be selected for the CAST's Young Talents Cultivation Program for Doctoral Students (中国科协青年人才培育工程-博士生专项计划) 🌱"


[[news]]
date = "2025"
content = "11-29: New preprint - [“Variational analysis of determinantal varieties”](https://arxiv.org/abs/2511.22613)"

[[news]]
date = "2025"
content = "09-30: Awarded the Hua Luogeng Scholarship at AMSS 🎖️"

[[news]]
date = "2025"
content = "05-05: Awarded the SIAM Certificate of Recognition 🎖️"

[[news]]
date = "2025"
content = "01-24: New preprint - [“A space-decoupling framework for optimization on bounded-rank matrices with orthogonally invariant constraints”](https://arxiv.org/abs/2501.13830)"


[[news]]
date = "2025"
content = "01-23: New paper accepted in AISTATS 2025 - [“Bilevel reinforcement learning via the development of hyper-gradient without lower-level convexity”](https://arxiv.org/abs/2405.19697)"

[[news]]
date = "2025"
content = "01-23: New paper accepted in ICLR 2025 - [“LancBiO: dynamic Lanczos-aided bilevel optimization via Krylov subspace”](https://arxiv.org/abs/2404.03331)"


# 🎉