
[[news]]
date = "2025"
content = "12-15: Honored to be selected for the Doctoral Fellowship under CAST’s Youth Talent Development Program (中国科协青年人才培育工程-博士生专项计划) 🌱"


[[news]]
date = "2025"
content = "11-29: New preprint - [“Variational analysis of determinantal varieties”](https://arxiv.org/abs/2511.22613)"

[[news]]
date = "2025"
content = "09-30: Awarded the Hua Luogeng Scholarship at AMSS 🎖️"

[[news]]
date = "2025"
content = "05-05: Awarded the SIAM Certificate of Recognition 🎖️"

[[news]]
date = "2025"
content = "01-24: New preprint - [“A space-decoupling framework for optimization on bounded-rank matrices with orthogonally invariant constraints”](https://arxiv.org/abs/2501.13830)"


[[news]]
date = "2025"
content = "01-23: New paper accepted in AISTATS 2025 - [“Bilevel Reinforcement Learning via the Development of Hyper-gradient without Lower-Level Convexity”](https://arxiv.org/abs/2405.19697)"

[[news]]
date = "2025"
content = "01-23: New paper accepted in ICLR 2025 - [“LancBiO: dynamic Lanczos-aided bilevel optimization via Krylov subspace”](https://arxiv.org/abs/2404.03331)"


# 🎉