[[news]]
date = "2026"
content = "06-27: Talk at CSIAM Youth Forum, Chengdu, China ([slides](/slides/GOTD_Chengdu.pdf), [CSIAM Youth Forum 2026](https://www.csiam.org.cn/1006/202606/2774.html))"


[[news]]
date = "2026"
content = "06-02: Talk at the session \"Geometric Constrained Optimization\" at SIAM Conference on Optimization, Edinburgh, United Kingdom ([slides](/slides/SecVar_Edinburgh.pdf), [OP26](https://www.siam.org/conferences-events/siam-conferences/op26/))"

[[news]]
date = "2026"
content = "04-11: Talk at the session \"Recent Advances in Riemannian Optimization\" at 2026 International Conference on Optimization: Techniques and Applications, Shanghai, China ([slides](/slides/SecVar_Shanghai.pdf), [ICOTA 2026](https://jcxy.sues.edu.cn/ICOTA2026/27096/list.htm))"

[[news]]
date = "2025"
content = "11-19: Talk at the Eighth Peking University Symposium for Top Doctoral Students in Computational and Applied Mathematics, Beijing, China ([slides](/slides/SpaceDecoupling.pdf))"

[[news]]
date = "2025"
content = "10-23: Poster at the Twenty-Third Annual Conference of China Society for Industrial and Applied Mathematics, Changsha, China ([poster](/posters/poster_CSIAM2025.pdf), [CSIAM 2025](https://meeting.csiam.org.cn/#/2025/))"

[[news]]
date = "2025"
content = "08-10: Talk at the China Conference on Scientific Machine Learning, Beijing, China ([slides](/slides/SoBiRL.pdf), [CSML2025](https://c2sml.cn/conference_en.html))"

[[news]]
date = "2025"
content = "05-03: Poster at the 28th International Conference on Artificial Intelligence and Statistics, Thailand ([poster](/posters/poster_AISTATS2025.pdf), [AISTATS 2025](https://aistats.org/aistats2025//))"

[[news]]
date = "2025"
content = "04-24: Poster at the Thirteenth International Conference on Learning Representations, Singapore ([poster](/posters/poster_ICLR2025.pdf), [ICLR 2025](https://iclr.cc/virtual/2025/poster/27854))"

